### ISSUE TITLE
Best engine given a time constraint

### ISSUE THREAD

**Issue by GabrielPereyra** [duilio/c4#1]
Engine/settings give the best performance given 1 second of processing time? Also, are there any obvious optimizations to be made? I'm happy to make a pull request with some guidance.

**Comment by duilio** [comment]
Hi Gabriel, probably a well tuned MCTS beats PVS. You can try it with the Arena command.

On the alphabeta family of engine probably the move ordering is something that can be improved significantly. I don't know if the Killer Heuristic may work in C4 (https://chessprogramming.wikispaces.com/Killer+Heuristic) it is probably worth trying it.

Also some kind of depth extension might be nice, for instance during a forced move. (basically you don't decrease the depth of the recursion in the case the player had just one available move or it is a forced move due to a c4 threat).

On the MCTS side you can introduce parallelism or experiment with machine learning. I have a simple ML player in my local branch but the problem is to create a dataset for learning.

Also an opening book might be worth. I have actually some code for it in local that I haven't pushed yet.

**Comment by duilio** [comment]
I have just pushed my last changes in the `mcts_priors` and `nn_wip` branches.
